# Generated by Django 6.0 on 2026-03-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Creating time of new')),
                ('header', models.CharField(max_length=200, verbose_name='Header of new')),
                ('text', models.TextField(verbose_name='Text of new')),
            ],
        ),
    ]
