# Generated by Django 6.0 on 2026-03-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schoolclasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200, verbose_name='Name of class')),
                ('class_level', models.IntegerField(verbose_name='Level of class')),
            ],
        ),
    ]
