# Generated by Django 6.0 on 2026-05-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='Bio of user'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthday_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday date of user'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ph Num of user'),
        ),
    ]
