# Generated by Django 6.0 on 2026-03-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_schoolclasses'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=str, upload_to='news/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
